databases:
  - name: my_db
    plan: free
    databaseName: djangodb
    user: db_user

services:
  - type: web
    name: django-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn newp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.2"