# Generated by Django 6.0.3 on 2026-04-04 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(upload_to='valgus_shop/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='preview_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='website',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
