# Generated by Django 6.0.3 on 2026-04-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_website_options_website_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='image',
        ),
    ]
