# Generated by Django 6.0.3 on 2026-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_website_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='image_filename',
            field=models.CharField(default='default.png', max_length=100),
            preserve_default=False,
        ),
    ]
