# Generated by Django 6.0.3 on 2026-04-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('main_title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=40)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
                ('lead_text', models.TextField(null=True)),
                ('sub_heading', models.CharField(max_length=30)),
                ('block_quote', models.TextField(null=True)),
                ('full_blog', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('color', models.CharField(default='#ff4d4d', max_length=7)),
                ('profile_image_filename', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(upload_to='blog_images/')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
